TECH-DEBT-9-Task-1
UB-ES-2020-A/Grup-ES pull request #153
Opened 2020-11-26 17:35 UTC by francinaPons

basic setup, more than one transaction at a time, it_transaction inicializes at __init__, relationship between transactions and users

2020-11-27 00:04 UTC, ferranSanchezUB requested changes

2020-11-27 00:04 UTC, ferranSanchezUB commented on backend/tests/test_COM_6.py
> +            self.assertEqual(1, len(TransactionsModel.find_by_id(1)))
el assert seria millor que comprovessis que l'element afegit sigui el que realment has especificat, perque el test et passa amb que `TransactionsModel.find_by_id(1)` retorni una llista amb un element. En plan:
```python
trans = TransactionsModel.find_by_id(1)
self.assertEqual(1, len(trans))
# O sino comprovar que el json sigui igual al esperat
self.assertEqual(self.book.isbn, trans.isbn)
# ...
```
Aplicable a tots els tests, no tels mencionare perque son masses.

2020-11-27 00:04 UTC, ferranSanchezUB commented on backend/tests/test_COM_6.py
Afegir test de afegir variis.

2020-11-27 09:52 UTC, francinaPons commented on backend/model/transactions.py
> +            transactions.append(transaction.json())
No no cal, per ara al mail hi ha el json, ja ho milloraré més endavant.

2020-11-27 09:54 UTC, francinaPons commented on backend/model/transactions.py
> +        atr['isbn'] = BooksModel.find_by_isbn(self.isbn).isbn
@gmolinga et va bé si et retorno el json de la transaction? O també necessites el json del llibre?
Per ara deixo que retorni el json de la transaction (p. ex: [{"id_transaction": 1, "isbn": 1, "price": 1.0, "id_user": 1, "quantity": 1, "date": "27-11-2020"}, {"id_transaction": 1, "isbn": 2, "price": 13.1, "id_user": 1, "quantity": 1, "date": "27-11-2020"}]

2020-11-27 10:51 UTC, ferranSanchezUB commented on backend/model/transactions.py
> +            transactions.append(transaction.json())
Si pero si els de front necesiten tota la info de llibre això no ho has passar al usuari a través del correu

2020-11-27 12:03 UTC, francinaPons commented on backend/model/transactions.py
> +        self.price = book.precio
fet

2020-11-27 12:04 UTC, francinaPons commented on backend/tests/test_COM_6.py
> +            self.assertEqual(1, len(TransactionsModel.find_by_id(1)))
Fet

2020-11-27 18:30 UTC, gmolinga commented on backend/model/transactions.py
> +        atr['isbn'] = BooksModel.find_by_isbn(self.isbn).isbn
Si pots passar el json del llibre millor. Perquè l'hauré de visualitzar.

2020-11-27 22:18 UTC, francinaPons commented on backend/model/transactions.py
> +            transactions.append(transaction.json())
Per ara en el mail també surt el json del llibre. Ho canviem en un futur perquè el mail sigui més bonic.

2020-11-28 08:16 UTC, gmolinga approved these changes

2020-11-28 10:07 UTC, ferranSanchezUB approved these changes

2020-11-28 10:15 UTC, merged