US-BIB-1-Task1
UB-ES-2020-A/Grup-ES pull request #159
Opened 2020-11-28 18:18 UTC by aaronPeruga

*Gestion de las diferentes listas de la biblioteca para poder buscar libros por estados

2020-11-28 18:49 UTC, paubernabe approved these changes

2020-11-29 10:43 UTC, gmolinga requested changes

2020-11-29 10:43 UTC, gmolinga commented on frontend/src/components/main.vue
> +      axios.get(path, params)
Aquest canvia fa que deixi de funcionar el GET correctament. Els parametres en un get s'envien com estaven abans.

2020-11-29 10:56 UTC, paubernabe commented on frontend/src/components/main.vue
> +      axios.get(path, params)
Si no recordo malament, d'aquesta manera també és vàlid, no? Ja que abans de fer aixó no li anava.

2020-11-29 12:16 UTC, gmolinga commented on frontend/src/components/main.vue
> +      axios.get(path, params)
D'aquesta manera no es vàlid, no s'envien els parametres. Podeu comprovar-ho posant un breakpoint al get a pycharm i veient quins parametres li arriben. És el que vam parlar de que el get d'axios no té el paràmetre params sinó que té el paràmetre opcional config.

2020-11-29 12:17 UTC, paubernabe commented on frontend/src/components/main.vue
> +      axios.get(path, params)
Perfecte, lapsus meu doncs.

2020-11-29 12:18 UTC, gmolinga approved these changes

2020-11-29 12:18 UTC, merged