Tech debt 15 task2
UB-ES-2020-A/Grup-ES pull request #233
Opened 2020-12-10 12:54 UTC by paubernabe

Millores generals de frontend:

* Imagenes carrusel bien recortadas para que esten bonitas 
* Crear vue-cards/loquesea para libros (escaparate,search) 
* Añadir el logo nuveo en la página
* Mensaje de cesta vacia
* Quitar Codigo de descuento
* Modales de añadir y modificar Más anchos y cambiar input de sinopsis a form-textarea 
* Navbar amplio.
* Quitar logs
* Página de Not Found
* Al recibir un 401, devolver a la página principal

2020-12-10 16:16 UTC, gmolinga approved these changes
Molt bon  treball

2020-12-10 16:26 UTC, gmolinga requested changes
Faria falta que adaptessis el test de :
test_get_book2 (tests.test_ESCP_4.UnitTestOfUS)
Al nou criteri

2020-12-10 16:29 UTC, paubernabe commented
> Faria falta que adaptessis el test de :
> test_get_book2 (tests.test_ESCP_4.UnitTestOfUS)
> Al nou criteri

@gmolinga entenc el que vols dir.  S'han de canviar varis EndPoints (Search i BookList) ja que no es va tenir en compte l'utilitat dels llibres no visibles a Stock.
@francinaPons si pots fer el push directament a la branca associada a aquest PR i ho enllestim

2020-12-10 23:33 UTC, ferranSanchezUB approved these changes

2020-12-10 23:42 UTC, aaronPeruga approved these changes

2020-12-11 12:43 UTC, francinaPons approved these changes

2020-12-11 12:45 UTC, gmolinga approved these changes

2020-12-11 12:48 UTC, merged